language: generic #fixes some Rakefile not found errors happening occasionally

sudo: required
services:
  - docker

before_install:
  - docker build -t docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true docker-react npm run test -- --coverage

deploy:
  secret_access_key: $AWS_SECRET_KEY
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-363500710113"
  bucket: "docker-react"
  on:
    branch: master
